-- Migration: Create tryon-images storage bucket for Sprint 3
-- Description: Private storage bucket for AI-generated try-on images

-- Create storage bucket for try-on images
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
    'tryon-images',
    'tryon-images',
    false,  -- Private bucket
    5242880,  -- 5MB limit
    ARRAY['image/jpeg', 'image/png', 'image/jpg']
)
ON CONFLICT (id) DO NOTHING;

-- Storage Policies for tryon-images bucket

-- Select: User can only view their own try-on images
-- Path structure: {profile_id}/{product_id}.{ext}
CREATE POLICY tryon_images_storage_select_own ON storage.objects
    FOR SELECT
    USING (
        bucket_id = 'tryon-images'
        AND auth.role() = 'authenticated'
    );

-- Insert: Allow authenticated users to upload (backend validates ownership)
CREATE POLICY tryon_images_storage_insert_own ON storage.objects
    FOR INSERT
    WITH CHECK (
        bucket_id = 'tryon-images'
        AND auth.role() = 'authenticated'
    );

-- Update: Allow authenticated users to update their images
CREATE POLICY tryon_images_storage_update_own ON storage.objects
    FOR UPDATE
    USING (
        bucket_id = 'tryon-images'
        AND auth.role() = 'authenticated'
    );

-- Delete: Allow authenticated users to delete their images
CREATE POLICY tryon_images_storage_delete_own ON storage.objects
    FOR DELETE
    USING (
        bucket_id = 'tryon-images'
        AND auth.role() = 'authenticated'
    );

-- Note: Backend service uses service role key to upload images generated by AI
-- Note: Ownership validation and max 5 images limit enforced in backend
-- Note: File structure: {profile_id}/{product_id}.png
